FROM alpine


RUN echo "**** install Python ****" && \
    apk add --no-cache python3 && \
    if [ ! -e /usr/bin/python ]; then ln -sf python3 /usr/bin/python ; fi && \
    \
    echo "**** install pip ****" && \
    python3 -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip3 install --no-cache --upgrade pip setuptools wheel && \
    if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
    echo "**** install vim ****" && \ 
    apk add vim  

WORKDIR /app
COPY . /app 

RUN pip install --requirement ./requirements.txt
EXPOSE 5000
CMD [ "python3", "./app.py" ]

